name: test-clang-format

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - './src/gamepad'
          - './include/gamepad'

    steps:
    - uses: actions/checkout@v2
    - uses: jidicula/clang-format-action@v4.14.0
      with:
        clang-format-version: '19'
        check-path: ${{ matrix.path }}
