name: Add Template to Pull Request 
on:
  workflow_run:
    workflows: ['Build Template']
    types: [completed]
jobs:
  pr_comment:
    # if Build Template was successful and ran on a branch that is currently the head in a pull request
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    permissions: 
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./pr-comment.js')
            await script({github, context, core})