name: Build Template

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: LemLib/pros-build@v1.0.0
        with:
          library-path: gamepad
