name: Build Release

on:
  release:
    types: [published]

jobs:
  build-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Template
        id: build_step
        uses: LemLib/pros-build@v2.0.2
        with:
          lib_folder_name: "gamepad"
          copy_readme_and_license_to_include: true
          no_commit_hash: true
      - name: Upload Template To Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ github.workspace }}/${{ steps.build_step.outputs.name }}
